apiVersion: v1
kind: PersistentVolume
metadata:
  name: sq-extensions
  annotations:
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    kind: PersistentVolumeClaim
    namespace: sq
    name: sq-extensions
  nfs:
    path: /var/nfs/sq
    server: 10.10.1.205
    readOnly: false
