apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "sonarqube.fullname" . }}
    labels:
        app: {{ include "sonarqube.name" .}}
spec:
    replicas: {{ .Values.replicaCount}}
    selector:
        matchLabels:
            app: {{ include "sonarqube.name" .}}
    template:
        metadata:
            labels:
                app: {{ include "sonarqube.name" .}}
        spec:
            containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: {{ .Values.service.targetPort }}
                  protocol: {{ .Values.service.protocol }}
              envFrom:
                - configMapRef:
                    name: sonarqube-config
                - secretRef:
                    name: sonarqube-secret
              env:
                - name: "SONARQUBE_JDBC_USERNAME"
                  value: "postgres"
                - name: "SONARQUBE_JDBC_URL"
                  value: "jdbc:postgresql://10.10.1.70:30002/postgres"
                - name: "SONARQUBE_JDBC_PASSWORD"
                  valueFrom:
                    secretKeyRef:
                      name: sonarqube-secret
                      key: password
              volumeMounts:
                {{- if .Values.conf.enabled }}
                - name: conf
                  mountPath: {{ .Values.conf.mountPath }}
                  subPath: {{ .Values.conf.subPath }}
                {{- end }}
                {{- if .Values.extensions.enabled }}
                - name: extensions
                  mountPath: {{ .Values.extensions.mountPath }}
                  subPath: {{ .Values.extensions.subPath }}
                {{- end }}
                {{- if .Values.logs.enabled }}
                - name: logs
                  mountPath: {{ .Values.logs.mountPath }}
                  subPath: {{ .Values.logs.subPath }}
                {{- end }}
                {{- if .Values.data.enabled }}
                - name: data
                  mountPath: {{ .Values.data.mountPath }}
                  subPath: {{ .Values.data.subPath }}
                {{- end }}
            volumes:
            - name: conf
              persistentVolumeClaim:
                claimName: sq-conf
            - name: extensions
              persistentVolumeClaim:
                claimName: sq-extensions
            - name: logs
              persistentVolumeClaim:
                claimName: sq-logs
            - name: data
              persistentVolumeClaim:
                claimName: sq-data

