apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: sonarqube-secret
data:

  SQ_DATASOURCE_USERNAME: {{ .Values.sq.datasource.username | b64enc }}
  SQ_DATASOURCE_PASSWORD: {{ .Values.sq.datasource.password | b64enc }}
